config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'likes/create'
  get 'comments/new'
  get 'comments/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope  :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for controllers: { registrations: 'registrations' }

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :new, :create, :destroy] do
          resources :comments, only: [:index, :new, :create, :destroy]
          resources :likes, only: [:create]
        end
      end    
    end  
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # Define User abilities
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Post, author: user
      can :manage, Comment, author: user
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, class_name: 'Post', foreign_key: :post_id

  after_save :update_counter
  def update_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post, class_name: 'Post', foreign_key: :post_id

  after_save :update_counter
  def update_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, foreign_key: :post_id, dependent: :destroy
  has_many :likes, foreign_key: :post_id, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_counter

  def update_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments
    comments.includes(:post).limit(5).order(created_at: :DESC)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true
  # validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.includes(:author).limit(3).order(created_at: :DESC)
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::API
  before_action :set_default_format

  private

  def set_default_format
    request.format = :json
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  before_action :authorize_request, only: [:create]

  # fetch user including their posts and comment and render
  def index
    @user = User.includes(posts: [:comments]).find(params[:user_id])
    @post = @user.posts.find_by(id: params[:post_id])
    render json: @post ? @post.comments : "No comment for post: #{params[:post_id]}"
  end

  # create a new comment associated with the post and render
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.post_id = @post.id
    render json: @comment if @comment.save
  end

  def comment_params
    params.require(:comment).permit(:text, :post_id, :author_id) # allow only certain parameters
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @post = @user.posts
    render json: @post, status: :ok
  end

  def show
    @post = Post.find(params[:id])
    render json: @post, status: :ok
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    render json: User.all
  end

  def show
    render json: @user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio email password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(author_id: current_user.id))

    if @comment.save
      flash[:success] = 'Comment successfully created'
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:error] = 'Error: Comment failed to save'
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    Comment.destroy(params[:id])
    @post.comments_counter -= 1
    @post.save
    redirect_to user_post_path(@user.id, @post.id)
  end

  private

  def comment_params
    if params.key?(:comment)
      params.require(:comment).permit(:text)
    else
      {}
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    if @like.save
      flash[:notice] = 'Like added successfully!'
      redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
    else
      flash[:alert] = "Couln't add like!"
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user, only: %i[index show]

  def index
    @posts = Post.all
  end

  def show
    @current_user = current_user
    @post = Post.find(params[:id])
    @comment = Comment.new
    @like = Like.new
    @user = User.find_by(id: params[:user_id])
  end

  def set_user
    @user = User.find(params[:user_id])
    @user_recent_posts = @user.recent_posts
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = 'Post successfully created'
          redirect_to "/users/#{current_user.id}/posts/#{@post.id}"
        else
          flash.now[:error] = 'Error: Post failed to save'
          render :new
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    current_user.posts_counter -= 1
    current_user.save
    redirect_to user_path(current_user.id)
    puts 'You are deleting this post'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :author_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    redirect_to new_user_session_path if current_user.nil?
    @users = User.all
  end

  def show
    @user_id = User.find(params[:id])
    @recent_posts = @user_id.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog App Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
     <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/partials/_comment-form.html.erb
<header>
  <h4>Add comment</h4>
</header>

<div>
  <%= form_with model: @comment, url:user_post_comments_path(user_id: @post.author.id, post_id: @post.id), method: :post, local: true do |form| %>
    <%= form.hidden_field :author_id, value: @post.author.id %>
    <%= form.hidden_field :post_id, value: @post.id %>
    <%= form.text_area :text, size: "80x4", placeholder: "Type comments here", required: true %>
    <%= form.submit "Add Comment", disable_with: "Submitting comment..." %>
  <% end %>
</div>

app/views/partials/_comment.html.erb
<% if post.comments.empty? %>
  <p>No comments yet.</p>
<% else %>
  <ul class= "border-black">
    <%# If there are comments, display them inside an unordered list element. %>
    <% post.comments.includes(:author).each do |comment| %>
    <li class="comment-list">
      <div class="comment-content">
        <p><%= "#{comment.author.name}: #{comment.text}" %></p>
      </div>
      <% if can? :destroy, comment %>
        <div class="delete-button-container">
          <%= form_with url: user_post_comment_path(post.author.id, @post.id, comment.id), :method => :delete do |f| %>
            <%= f.submit 'Delete comment', class: 'delete-button' %>
          <% end %>
        </div>
      <% end %>
    </li>
  <% end %>
  </ul>
<% end %>

app/views/partials/_like-form.html.erb
<div>
  <%= form_with url:user_post_likes_path(user_id: @post.author.id, post_id: @post.id), method: :post, local: true do |form| %>
    <%= form.hidden_field :author_id, value: @post.author.id %>
    <%= form.hidden_field :post_id, value: @post.id %>
    <%= form.submit "Like", disable_with: "Updating likes..." %>
  <% end %>
</div>

app/views/partials/_post.html.erb
<div class="post">
  <%# Contains the post title as a hyperlink that is generated by a link_to helper method with two parameters: id and user_id %>
  <h3><%= link_to(post.title, user_post_path(post.author_id, post.id)) %></h3>

  <%# containing the truncated post text generated by the truncate helper method, with an ellipsis at the end %>
  <p><%= truncate(post.text, length: 150, omission: "...") %></p>
  
  <%# With a class of reactions containing the post's comment and like counters %>
  <div class="reactions">
    <span>Comments <%= post.comments_counter %>, </span>
    <span>Likes <%= post.likes_counter %></span>
    <% if can? :destroy, post %>
      <%= form_with url: user_post_path(post.author_id, post.id), :method => :delete do |f| %>
        <%= f.submit 'Delete post', class: 'post-delete-button' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/partials/_user.html.erb
<!-- Adds a stylesheet link to a CSS file -->
<link rel="stylesheet" href="/assets/user.css">

<!-- Creates a section for user information -->
<div class="user">
  <%= link_to(image_tag('user.jpg', alt: 'User', class: 'user__image'), user_path(user)) %>

  <!-- Displays user information together with number of posts-->
  <%= link_to(user_path(user)) do %>
    <div class="user__info">
      <h2><%= user.name %></h2>
      <p>Number of Posts: <%= user.posts_counter || 0 %></p>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<header>
  <h1 class= "title">List of User's Posts</h1>
</header>

<%# Renders partial view for the user section of the page, passing in the @user variable %>
<%= render 'partials/user', user: @user %>

<%# Loops through each of the user's recent posts and renders a partial view for each post, passing in the post variable %>
<% @user_recent_posts.each do |post| %>
  <%# Renders partial view for the post section of the page, passing in the post variable %>
  <%= render 'partials/post', post: post %>

    <ul class="comments">
      <% post.recent_comments.includes(:author).each do |comment| %>
         <%# A list item element with the author's name and the text of the comment %>
        <li class="comment-list">
          <div class="comment-content">
            <p><%= "#{comment.author.name}: #{comment.text}" %></p>
          </div>
          <% if can? :destroy, comment %>
            <div class="delete-button-container">
              <%= form_with url: user_post_comment_path(post.author.id, post.id, comment.id), :method => :delete do |f| %>
                <%= f.submit 'Delete comment', class: 'delete-button' %>
              <% end %>
            </div>
          <% end %>
        </li>
    </ul>
  <% end %>
<% end %>
<%= link_to 'create new post', new_user_post_path(@user.id), class: "button" %>

app/views/posts/new.html.erb
<header>
  <h1 class= "title">Create a Post</h1>
</header>

<div>
  <%= form_with model: @post, url: user_posts_path, class: "post-form", method: :post, local: true do |form| %>

    <% if @post.errors.any? %>
      <ul class="errors">
        <% @post.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    <% end %>

    <div>
      <%= form.label :title, "Title"%>
      <%= form.text_field :title, placeholder: 'Enter post title', class:'title-input' %>
    </div>

    <div>
      <%= form.label :text, "Content" %>
      <%= form.text_area :text, placeholder: 'Write your post', class: 'text-input' %>
    </div>
    
    <div>
      <%= form.submit 'Submit Post', class: 'button', id:'post-btn' %>
    <div>

  <% end %>
</div>

app/views/posts/show.html.erb
<header>
<h1 class= "title">Single Post View</h1>
</header>

<div class="single-post">

  <%# Contains the information about the post, including the post id and author name %>
  <div class="post-info">
    <h2><%= @post.title%></h2>
    <p class="post-likes-comments">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
  </div>
  <h3>Post # <%= @post.id %> by <%= @post.author.name %></h3>
  <p> <%= @post.text %></p>

  <%# Contains the comments for the post and renders the comment partial %>
  <div class="comments">
    <%= render "partials/comment", post: @post %>
  </div>
 
  <%= render partial: "partials/comment-form", local: {user: @current_user.id, post: @post} %>
  <%= render "partials/like-form", post: @post %>

  <% if can? :destroy, @post %>
    <%= form_with url: user_post_path(@current_user.id, @post.id), method: :delete do |f| %>
      <%= f.submit 'Delete post', class: 'post-delete-button' %>
    <% end %>
  <% end %>

</div>

app/views/users/index.html.erb
<section>
  <h1 class="title">List of all Users</h1>
  <ul>
    <% @users.each do |user| %>
      <%= render "partials/user", user: user %>
    <% end %>
  </ul>
</section>

app/views/users/show.html.erb
<header>
  <h1 class="title">User Profile</h1>
</header>

<%# Renders partial view for the user section of the page, passing in the @user variable %>
<%= render 'partials/user', user: @user_id %>

<section class="bio">
  <h2>User Bio</h2>
  <p><%= @user_id.bio %></p>
</section>

<%# Loops through each of the user's recent posts and renders a partial view for each post, passing in the post variable %>
<% @recent_posts.each do |post| %>
  <%= render partial: 'partials/post', locals: { post: post} %>
<% end %>

<%# Creates a link to the user's posts page %>
<%= link_to "See all Posts", user_posts_path(@user_id), class: "button" %>